/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    categories: Category;
    posts: Post;
    projects: Project;
    links: Link;
    'favourite-media': FavouriteMedia;
    notes: Note;
    'web-apps': WebApp;
    'guestbook-entries': GuestbookEntry;
    'media-types': MediaType;
    'media-statuses': MediaStatus;
    'project-statuses': ProjectStatus;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    'favourite-media': FavouriteMediaSelect<false> | FavouriteMediaSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    'web-apps': WebAppsSelect<false> | WebAppsSelect<true>;
    'guestbook-entries': GuestbookEntriesSelect<false> | GuestbookEntriesSelect<true>;
    'media-types': MediaTypesSelect<false> | MediaTypesSelect<true>;
    'media-statuses': MediaStatusesSelect<false> | MediaStatusesSelect<true>;
    'project-statuses': ProjectStatusesSelect<false> | ProjectStatusesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-identity': SiteIdentity;
  };
  globalsSelect: {
    'site-identity': SiteIdentitySelect<false> | SiteIdentitySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * Profile photo displayed on the site
   */
  avatar?: (number | null) | Media;
  handle?: string | null;
  role: 'admin' | 'editor' | 'api';
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  /**
   * Optional description shown in the gazette sidebar
   */
  description?: string | null;
  /**
   * Image icon shown in the sidebar folder
   */
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  featured?: boolean | null;
  publishedAt?: string | null;
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  summary: string;
  /**
   * Project status (configured in Project Statuses)
   */
  projectStatus: number | ProjectStatus;
  featured?: boolean | null;
  order: number;
  stack?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  repositoryUrl?: string | null;
  externalUrl?: string | null;
  coverImage?: (number | null) | Media;
  tags?: (number | Tag)[] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Status definitions for Projects — controls label, color, and icon
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-statuses".
 */
export interface ProjectStatus {
  id: number;
  /**
   * Slug key used in Project entries (e.g. "active", "building", "planned", "concept", "archived")
   */
  value: string;
  /**
   * Display name shown on project cards (e.g. "Active", "Building")
   */
  label: string;
  /**
   * CSS color value for this status badge (e.g. "oklch(72% 0.14 80)" or "#4ade80")
   */
  color?: string | null;
  /**
   * Image icon for this status (preferred over glyph)
   */
  icon?: (number | null) | Media;
  /**
   * ASCII/symbol fallback if no icon image (e.g. "●", "◐", "○")
   */
  glyph?: string | null;
  /**
   * Sort order (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  label: string;
  platform: string;
  href: string;
  description: string;
  /**
   * ASCII/emoji fallback when no logo is set (e.g. "{}", "@", "in")
   */
  icon?: string | null;
  logo?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourite-media".
 */
export interface FavouriteMedia {
  id: number;
  title: string;
  /**
   * Author, artist, studio, or developer (shown on Now cards)
   */
  creator?: string | null;
  slug: string;
  /**
   * Type of media (configured in Media Types)
   */
  mediaType: number | MediaType;
  /**
   * Current progress/status (configured in Media Statuses)
   */
  progress: number | MediaStatus;
  /**
   * Rating from 1 to 10
   */
  rating?: number | null;
  /**
   * Short review or thoughts
   */
  review?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Cover image URL from external API (used if no uploaded cover)
   */
  externalCoverUrl?: string | null;
  /**
   * ID from external API (IGDB, TMDB, AniList, etc.)
   */
  externalId?: string | null;
  /**
   * Source API (igdb, tmdb, anilist, etc.)
   */
  externalSource?: string | null;
  /**
   * Link to the item on the external site
   */
  externalUrl?: string | null;
  /**
   * Link to a blog post with a full review
   */
  blogPost?: (number | null) | Post;
  /**
   * Link to a review on a third-party site (MAL, Steam, Letterboxd, etc.)
   */
  externalReviewUrl?: string | null;
  /**
   * When you finished / last interacted with it
   */
  completedAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Media type definitions: display label, icon, and "Now X" widget category
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-types".
 */
export interface MediaType {
  id: number;
  /**
   * Slug key — must match the value used in Favourite Media entries (e.g. "anime", "game", "book")
   */
  value: string;
  /**
   * Display name shown in filters and cards (e.g. "Anime", "Games")
   */
  label: string;
  /**
   * Image icon shown in filters and cards (preferred over glyph)
   */
  icon?: (number | null) | Media;
  /**
   * ASCII/text fallback if no icon image is set (e.g. ">>")
   */
  glyph?: string | null;
  /**
   * Which "Now X" widget this media type belongs to on the media app
   */
  nowCategory: 'none' | 'watching' | 'reading' | 'playing' | 'listening';
  /**
   * Custom label for the "Now X" widget (e.g. "Now watching"). Only used if nowCategory is not "none".
   */
  nowLabel?: string | null;
  /**
   * Sort order in filter tabs (lower = first)
   */
  order: number;
  /**
   * External API to fetch metadata from when adding new entries
   */
  lookupSource?: ('none' | 'igdb' | 'tmdb' | 'anilist-anime' | 'anilist-manga' | 'openlibrary' | 'musicbrainz') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Progress/status definitions for Favourite Media entries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-statuses".
 */
export interface MediaStatus {
  id: number;
  /**
   * Slug key used in Favourite Media entries (e.g. "completed", "in-progress", "dropped", "planned")
   */
  value: string;
  /**
   * Display name shown in tags and detail views (e.g. "Completed")
   */
  label: string;
  /**
   * Image icon for this status (preferred over glyph)
   */
  icon?: (number | null) | Media;
  /**
   * ASCII/symbol fallback if no icon image (e.g. "✓", "▶", "✕", "◌")
   */
  glyph?: string | null;
  /**
   * Sort order in status filters (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Markdown files shown as a folder on the desktop
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  slug: string;
  /**
   * Filename shown on the desktop (e.g. "readme.md", "notes.md")
   */
  filename: string;
  /**
   * Plain markdown text. Rendered in the Notes desktop app.
   */
  content: string;
  /**
   * Date shown next to the filename on the desktop
   */
  publishedAt?: string | null;
  /**
   * Sort order in the desktop folder (lower = first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * External websites that appear as browser windows in the desktop
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-apps".
 */
export interface WebApp {
  id: number;
  /**
   * Display name in the window title bar and app menu
   */
  title: string;
  slug: string;
  /**
   * Full URL to embed (e.g. https://cv.sigterm.vodka)
   */
  url: string;
  /**
   * ASCII/emoji glyph for desktop icon and taskbar (e.g. "◎", "CV", "📄")
   */
  icon?: string | null;
  /**
   * Short description shown in tooltips or app menu
   */
  description?: string | null;
  /**
   * Default window size as percentage of screen
   */
  defaultSize?: {
    /**
     * Width in % (30-100)
     */
    width?: number | null;
    /**
     * Height in % (30-100)
     */
    height?: number | null;
  };
  /**
   * Show the browser address bar with the URL
   */
  showAddressBar?: boolean | null;
  /**
   * Show as a desktop icon
   */
  showInDesktop?: boolean | null;
  /**
   * Show in the mobile app menu
   */
  showInMenu?: boolean | null;
  /**
   * Enable/disable this web app
   */
  enabled?: boolean | null;
  /**
   * Lower numbers appear first in lists
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guestbook entries submitted by visitors. Approve to display on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook-entries".
 */
export interface GuestbookEntry {
  id: number;
  /**
   * Title of the entry
   */
  message: string;
  /**
   * Display name from Discord
   */
  authorName: string;
  /**
   * Avatar URL from Discord
   */
  authorAvatar?: string | null;
  /**
   * Discord user ID (for deduplication/banning)
   */
  authorDiscordId?: string | null;
  /**
   * Clerk user ID
   */
  clerkUserId?: string | null;
  /**
   * The canvas image (exported PNG from Excalidraw)
   */
  image: number | Media;
  /**
   * Optional Spotify or YouTube URL to embed alongside the entry
   */
  embedUrl?: string | null;
  /**
   * Auto-detected from embedUrl, or set manually
   */
  embedType?: ('none' | 'spotify' | 'youtube') | null;
  /**
   * Only approved entries are visible on the site
   */
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'favourite-media';
        value: number | FavouriteMedia;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'web-apps';
        value: number | WebApp;
      } | null)
    | ({
        relationTo: 'guestbook-entries';
        value: number | GuestbookEntry;
      } | null)
    | ({
        relationTo: 'media-types';
        value: number | MediaType;
      } | null)
    | ({
        relationTo: 'media-statuses';
        value: number | MediaStatus;
      } | null)
    | ({
        relationTo: 'project-statuses';
        value: number | ProjectStatus;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  avatar?: T;
  handle?: T;
  role?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  featured?: T;
  publishedAt?: T;
  category?: T;
  tags?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  projectStatus?: T;
  featured?: T;
  order?: T;
  stack?:
    | T
    | {
        label?: T;
        id?: T;
      };
  repositoryUrl?: T;
  externalUrl?: T;
  coverImage?: T;
  tags?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  label?: T;
  platform?: T;
  href?: T;
  description?: T;
  icon?: T;
  logo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourite-media_select".
 */
export interface FavouriteMediaSelect<T extends boolean = true> {
  title?: T;
  creator?: T;
  slug?: T;
  mediaType?: T;
  progress?: T;
  rating?: T;
  review?: T;
  coverImage?: T;
  externalCoverUrl?: T;
  externalId?: T;
  externalSource?: T;
  externalUrl?: T;
  blogPost?: T;
  externalReviewUrl?: T;
  completedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  filename?: T;
  content?: T;
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-apps_select".
 */
export interface WebAppsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  icon?: T;
  description?: T;
  defaultSize?:
    | T
    | {
        width?: T;
        height?: T;
      };
  showAddressBar?: T;
  showInDesktop?: T;
  showInMenu?: T;
  enabled?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook-entries_select".
 */
export interface GuestbookEntriesSelect<T extends boolean = true> {
  message?: T;
  authorName?: T;
  authorAvatar?: T;
  authorDiscordId?: T;
  clerkUserId?: T;
  image?: T;
  embedUrl?: T;
  embedType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-types_select".
 */
export interface MediaTypesSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  icon?: T;
  glyph?: T;
  nowCategory?: T;
  nowLabel?: T;
  order?: T;
  lookupSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-statuses_select".
 */
export interface MediaStatusesSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  icon?: T;
  glyph?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-statuses_select".
 */
export interface ProjectStatusesSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  color?: T;
  icon?: T;
  glyph?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site identity, operator profile, and terminal config
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity".
 */
export interface SiteIdentity {
  id: number;
  /**
   * Used in page titles and OG tags
   */
  siteName?: string | null;
  siteDomain?: string | null;
  siteEmail?: string | null;
  /**
   * Default meta description for the site
   */
  siteDescription?: string | null;
  /**
   * Default desktop wallpaper image
   */
  wallpaper?: (number | null) | Media;
  handle?: string | null;
  /**
   * Alternative handles / usernames
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  role?: string | null;
  specialty?: string | null;
  status?: ('active' | 'away' | 'inactive') | null;
  /**
   * Short tagline shown in profile
   */
  claim?: string | null;
  /**
   * One-line intro shown in dossier header
   */
  intro?: string | null;
  /**
   * Bio paragraphs shown in the dossier app
   */
  bio?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Profile photo shown in dossier
   */
  avatar?: (number | null) | Media;
  /**
   * Tags shown in the Inspirations section of dossier
   */
  inspirations?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Title shown at the top of the README window
   */
  navGuideTitle?: string | null;
  /**
   * Lines of text shown in the README.txt desktop app
   */
  navGuideLines?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shell prompt string shown in the terminal
   */
  terminalPrompt?: string | null;
  /**
   * Output of the `pwd` command
   */
  terminalPwd?: string | null;
  /**
   * Output of the `uname -a` command
   */
  terminalUname?: string | null;
  /**
   * Full text block output of the `whoami` terminal command
   */
  whoamiOutput?: string | null;
  /**
   * Full neofetch-style ASCII art output. Leave empty to use the default. Use a strict monospace font for proper alignment.
   */
  neofetchOutput?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity_select".
 */
export interface SiteIdentitySelect<T extends boolean = true> {
  siteName?: T;
  siteDomain?: T;
  siteEmail?: T;
  siteDescription?: T;
  wallpaper?: T;
  handle?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  role?: T;
  specialty?: T;
  status?: T;
  claim?: T;
  intro?: T;
  bio?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  avatar?: T;
  inspirations?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  navGuideTitle?: T;
  navGuideLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  terminalPrompt?: T;
  terminalPwd?: T;
  terminalUname?: T;
  whoamiOutput?: T;
  neofetchOutput?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}