/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'editor'])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum__posts_v_version_status = pgEnum('enum__posts_v_version_status', [
  'draft',
  'published',
])
export const enum_projects_status = pgEnum('enum_projects_status', ['draft', 'published'])
export const enum__projects_v_version_status = pgEnum('enum__projects_v_version_status', [
  'draft',
  'published',
])
export const enum_favourite_media_status = pgEnum('enum_favourite_media_status', [
  'draft',
  'published',
])
export const enum__favourite_media_v_version_status = pgEnum(
  'enum__favourite_media_v_version_status',
  ['draft', 'published'],
)
export const enum_notes_status = pgEnum('enum_notes_status', ['draft', 'published'])
export const enum__notes_v_version_status = pgEnum('enum__notes_v_version_status', [
  'draft',
  'published',
])
export const enum_media_types_now_category = pgEnum('enum_media_types_now_category', [
  'none',
  'watching',
  'reading',
  'playing',
  'listening',
])
export const enum_media_types_lookup_source = pgEnum('enum_media_types_lookup_source', [
  'none',
  'igdb',
  'tmdb',
  'anilist-anime',
  'anilist-manga',
  'openlibrary',
  'musicbrainz',
])
export const enum_site_identity_status = pgEnum('enum_site_identity_status', [
  'active',
  'away',
  'inactive',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    displayName: varchar('display_name'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    handle: varchar('handle').default('sigterm015'),
    role: enum_users_role('role').notNull().default('admin'),
    totpSecret: varchar('totp_secret'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_avatar_idx').on(columns.avatar),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    caption: varchar('caption'),
    credit: varchar('credit'),
    prefix: varchar('prefix').default('templ3/media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_card_url: varchar('sizes_card_url'),
    sizes_card_width: numeric('sizes_card_width', { mode: 'number' }),
    sizes_card_height: numeric('sizes_card_height', { mode: 'number' }),
    sizes_card_mimeType: varchar('sizes_card_mime_type'),
    sizes_card_filesize: numeric('sizes_card_filesize', { mode: 'number' }),
    sizes_card_filename: varchar('sizes_card_filename'),
    sizes_hero_url: varchar('sizes_hero_url'),
    sizes_hero_width: numeric('sizes_hero_width', { mode: 'number' }),
    sizes_hero_height: numeric('sizes_hero_height', { mode: 'number' }),
    sizes_hero_mimeType: varchar('sizes_hero_mime_type'),
    sizes_hero_filesize: numeric('sizes_hero_filesize', { mode: 'number' }),
    sizes_hero_filename: varchar('sizes_hero_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename),
    index('media_sizes_hero_sizes_hero_filename_idx').on(columns.sizes_hero_filename),
  ],
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    color: varchar('color').default('#b00b69'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tags_slug_idx').on(columns.slug),
    index('tags_updated_at_idx').on(columns.updatedAt),
    index('tags_created_at_idx').on(columns.createdAt),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_icon_idx').on(columns.icon),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    excerpt: varchar('excerpt'),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(false),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    content: jsonb('content'),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    seo_canonicalUrl: varchar('seo_canonical_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_hero_image_idx').on(columns.heroImage),
    index('posts_category_idx').on(columns.category),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
    index('posts__status_idx').on(columns._status),
  ],
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'posts_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_excerpt: varchar('version_excerpt'),
    version_heroImage: integer('version_hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_featured: boolean('version_featured').default(false),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_category: integer('version_category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_content: jsonb('version_content'),
    version_seo_metaTitle: varchar('version_seo_meta_title'),
    version_seo_metaDescription: varchar('version_seo_meta_description'),
    version_seo_canonicalUrl: varchar('version_seo_canonical_url'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_posts_v_parent_idx').on(columns.parent),
    index('_posts_v_version_version_slug_idx').on(columns.version_slug),
    index('_posts_v_version_version_hero_image_idx').on(columns.version_heroImage),
    index('_posts_v_version_version_category_idx').on(columns.version_category),
    index('_posts_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_posts_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_posts_v_version_version__status_idx').on(columns.version__status),
    index('_posts_v_created_at_idx').on(columns.createdAt),
    index('_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_posts_v_latest_idx').on(columns.latest),
  ],
)

export const _posts_v_rels = pgTable(
  '_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('_posts_v_rels_order_idx').on(columns.order),
    index('_posts_v_rels_parent_idx').on(columns.parent),
    index('_posts_v_rels_path_idx').on(columns.path),
    index('_posts_v_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: '_posts_v_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const projects_stack = pgTable(
  'projects_stack',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
  },
  (columns) => [
    index('projects_stack_order_idx').on(columns._order),
    index('projects_stack_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects.id],
      name: 'projects_stack_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    summary: varchar('summary'),
    projectStatus: integer('project_status_id').references(() => project_statuses.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(false),
    order: numeric('order', { mode: 'number' }).default(0),
    repositoryUrl: varchar('repository_url'),
    externalUrl: varchar('external_url'),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    content: jsonb('content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_projects_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('projects_slug_idx').on(columns.slug),
    index('projects_project_status_idx').on(columns.projectStatus),
    index('projects_cover_image_idx').on(columns.coverImage),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
    index('projects__status_idx').on(columns._status),
  ],
)

export const projects_rels = pgTable(
  'projects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('projects_rels_order_idx').on(columns.order),
    index('projects_rels_parent_idx').on(columns.parent),
    index('projects_rels_path_idx').on(columns.path),
    index('projects_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [projects.id],
      name: 'projects_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'projects_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const _projects_v_version_stack = pgTable(
  '_projects_v_version_stack',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    label: varchar('label'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_projects_v_version_stack_order_idx').on(columns._order),
    index('_projects_v_version_stack_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_projects_v.id],
      name: '_projects_v_version_stack_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _projects_v = pgTable(
  '_projects_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => projects.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_summary: varchar('version_summary'),
    version_projectStatus: integer('version_project_status_id').references(
      () => project_statuses.id,
      {
        onDelete: 'set null',
      },
    ),
    version_featured: boolean('version_featured').default(false),
    version_order: numeric('version_order', { mode: 'number' }).default(0),
    version_repositoryUrl: varchar('version_repository_url'),
    version_externalUrl: varchar('version_external_url'),
    version_coverImage: integer('version_cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_content: jsonb('version_content'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__projects_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_projects_v_parent_idx').on(columns.parent),
    index('_projects_v_version_version_slug_idx').on(columns.version_slug),
    index('_projects_v_version_version_project_status_idx').on(columns.version_projectStatus),
    index('_projects_v_version_version_cover_image_idx').on(columns.version_coverImage),
    index('_projects_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_projects_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_projects_v_version_version__status_idx').on(columns.version__status),
    index('_projects_v_created_at_idx').on(columns.createdAt),
    index('_projects_v_updated_at_idx').on(columns.updatedAt),
    index('_projects_v_latest_idx').on(columns.latest),
  ],
)

export const _projects_v_rels = pgTable(
  '_projects_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('_projects_v_rels_order_idx').on(columns.order),
    index('_projects_v_rels_parent_idx').on(columns.parent),
    index('_projects_v_rels_path_idx').on(columns.path),
    index('_projects_v_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_projects_v.id],
      name: '_projects_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: '_projects_v_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const links = pgTable(
  'links',
  {
    id: serial('id').primaryKey(),
    label: varchar('label').notNull(),
    platform: varchar('platform').notNull(),
    href: varchar('href').notNull(),
    description: varchar('description').notNull(),
    icon: varchar('icon'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('links_logo_idx').on(columns.logo),
    index('links_updated_at_idx').on(columns.updatedAt),
    index('links_created_at_idx').on(columns.createdAt),
  ],
)

export const favourite_media = pgTable(
  'favourite_media',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    creator: varchar('creator'),
    slug: varchar('slug'),
    mediaType: integer('media_type_id').references(() => media_types.id, {
      onDelete: 'set null',
    }),
    progress: integer('progress_id').references(() => media_statuses.id, {
      onDelete: 'set null',
    }),
    rating: numeric('rating', { mode: 'number' }),
    review: varchar('review'),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    externalCoverUrl: varchar('external_cover_url'),
    externalId: varchar('external_id'),
    externalSource: varchar('external_source'),
    externalUrl: varchar('external_url'),
    blogPost: integer('blog_post_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    externalReviewUrl: varchar('external_review_url'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    featured: boolean('featured').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_favourite_media_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('favourite_media_slug_idx').on(columns.slug),
    index('favourite_media_media_type_idx').on(columns.mediaType),
    index('favourite_media_progress_idx').on(columns.progress),
    index('favourite_media_cover_image_idx').on(columns.coverImage),
    index('favourite_media_blog_post_idx').on(columns.blogPost),
    index('favourite_media_updated_at_idx').on(columns.updatedAt),
    index('favourite_media_created_at_idx').on(columns.createdAt),
    index('favourite_media__status_idx').on(columns._status),
  ],
)

export const _favourite_media_v = pgTable(
  '_favourite_media_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => favourite_media.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_creator: varchar('version_creator'),
    version_slug: varchar('version_slug'),
    version_mediaType: integer('version_media_type_id').references(() => media_types.id, {
      onDelete: 'set null',
    }),
    version_progress: integer('version_progress_id').references(() => media_statuses.id, {
      onDelete: 'set null',
    }),
    version_rating: numeric('version_rating', { mode: 'number' }),
    version_review: varchar('version_review'),
    version_coverImage: integer('version_cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_externalCoverUrl: varchar('version_external_cover_url'),
    version_externalId: varchar('version_external_id'),
    version_externalSource: varchar('version_external_source'),
    version_externalUrl: varchar('version_external_url'),
    version_blogPost: integer('version_blog_post_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_externalReviewUrl: varchar('version_external_review_url'),
    version_completedAt: timestamp('version_completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_featured: boolean('version_featured').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__favourite_media_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_favourite_media_v_parent_idx').on(columns.parent),
    index('_favourite_media_v_version_version_slug_idx').on(columns.version_slug),
    index('_favourite_media_v_version_version_media_type_idx').on(columns.version_mediaType),
    index('_favourite_media_v_version_version_progress_idx').on(columns.version_progress),
    index('_favourite_media_v_version_version_cover_image_idx').on(columns.version_coverImage),
    index('_favourite_media_v_version_version_blog_post_idx').on(columns.version_blogPost),
    index('_favourite_media_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_favourite_media_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_favourite_media_v_version_version__status_idx').on(columns.version__status),
    index('_favourite_media_v_created_at_idx').on(columns.createdAt),
    index('_favourite_media_v_updated_at_idx').on(columns.updatedAt),
    index('_favourite_media_v_latest_idx').on(columns.latest),
  ],
)

export const notes = pgTable(
  'notes',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    filename: varchar('filename'),
    content: varchar('content'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_notes_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('notes_slug_idx').on(columns.slug),
    index('notes_updated_at_idx').on(columns.updatedAt),
    index('notes_created_at_idx').on(columns.createdAt),
    index('notes__status_idx').on(columns._status),
  ],
)

export const _notes_v = pgTable(
  '_notes_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => notes.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_filename: varchar('version_filename'),
    version_content: varchar('version_content'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_order: numeric('version_order', { mode: 'number' }).default(0),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__notes_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_notes_v_parent_idx').on(columns.parent),
    index('_notes_v_version_version_slug_idx').on(columns.version_slug),
    index('_notes_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_notes_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_notes_v_version_version__status_idx').on(columns.version__status),
    index('_notes_v_created_at_idx').on(columns.createdAt),
    index('_notes_v_updated_at_idx').on(columns.updatedAt),
    index('_notes_v_latest_idx').on(columns.latest),
  ],
)

export const web_apps = pgTable(
  'web_apps',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    url: varchar('url').notNull(),
    icon: varchar('icon').default('◎'),
    description: varchar('description'),
    defaultSize_width: numeric('default_size_width', { mode: 'number' }).default(80),
    defaultSize_height: numeric('default_size_height', { mode: 'number' }).default(85),
    showAddressBar: boolean('show_address_bar').default(true),
    showInDesktop: boolean('show_in_desktop').default(true),
    showInMenu: boolean('show_in_menu').default(true),
    enabled: boolean('enabled').default(true),
    sortOrder: numeric('sort_order', { mode: 'number' }).default(100),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('web_apps_slug_idx').on(columns.slug),
    index('web_apps_updated_at_idx').on(columns.updatedAt),
    index('web_apps_created_at_idx').on(columns.createdAt),
  ],
)

export const media_types = pgTable(
  'media_types',
  {
    id: serial('id').primaryKey(),
    value: varchar('value').notNull(),
    label: varchar('label').notNull(),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    glyph: varchar('glyph'),
    nowCategory: enum_media_types_now_category('now_category').notNull().default('none'),
    nowLabel: varchar('now_label'),
    order: numeric('order', { mode: 'number' }).notNull().default(0),
    lookupSource: enum_media_types_lookup_source('lookup_source').default('none'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('media_types_value_idx').on(columns.value),
    index('media_types_icon_idx').on(columns.icon),
    index('media_types_updated_at_idx').on(columns.updatedAt),
    index('media_types_created_at_idx').on(columns.createdAt),
  ],
)

export const media_statuses = pgTable(
  'media_statuses',
  {
    id: serial('id').primaryKey(),
    value: varchar('value').notNull(),
    label: varchar('label').notNull(),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    glyph: varchar('glyph'),
    order: numeric('order', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('media_statuses_value_idx').on(columns.value),
    index('media_statuses_icon_idx').on(columns.icon),
    index('media_statuses_updated_at_idx').on(columns.updatedAt),
    index('media_statuses_created_at_idx').on(columns.createdAt),
  ],
)

export const project_statuses = pgTable(
  'project_statuses',
  {
    id: serial('id').primaryKey(),
    value: varchar('value').notNull(),
    label: varchar('label').notNull(),
    color: varchar('color'),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    glyph: varchar('glyph'),
    order: numeric('order', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('project_statuses_value_idx').on(columns.value),
    index('project_statuses_icon_idx').on(columns.icon),
    index('project_statuses_updated_at_idx').on(columns.updatedAt),
    index('project_statuses_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    tagsID: integer('tags_id'),
    categoriesID: integer('categories_id'),
    postsID: integer('posts_id'),
    projectsID: integer('projects_id'),
    linksID: integer('links_id'),
    'favourite-mediaID': integer('favourite_media_id'),
    notesID: integer('notes_id'),
    'web-appsID': integer('web_apps_id'),
    'media-typesID': integer('media_types_id'),
    'media-statusesID': integer('media_statuses_id'),
    'project-statusesID': integer('project_statuses_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_tags_id_idx').on(columns.tagsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_links_id_idx').on(columns.linksID),
    index('payload_locked_documents_rels_favourite_media_id_idx').on(columns['favourite-mediaID']),
    index('payload_locked_documents_rels_notes_id_idx').on(columns.notesID),
    index('payload_locked_documents_rels_web_apps_id_idx').on(columns['web-appsID']),
    index('payload_locked_documents_rels_media_types_id_idx').on(columns['media-typesID']),
    index('payload_locked_documents_rels_media_statuses_id_idx').on(columns['media-statusesID']),
    index('payload_locked_documents_rels_project_statuses_id_idx').on(
      columns['project-statusesID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['linksID']],
      foreignColumns: [links.id],
      name: 'payload_locked_documents_rels_links_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['favourite-mediaID']],
      foreignColumns: [favourite_media.id],
      name: 'payload_locked_documents_rels_favourite_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notesID']],
      foreignColumns: [notes.id],
      name: 'payload_locked_documents_rels_notes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['web-appsID']],
      foreignColumns: [web_apps.id],
      name: 'payload_locked_documents_rels_web_apps_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['media-typesID']],
      foreignColumns: [media_types.id],
      name: 'payload_locked_documents_rels_media_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['media-statusesID']],
      foreignColumns: [media_statuses.id],
      name: 'payload_locked_documents_rels_media_statuses_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['project-statusesID']],
      foreignColumns: [project_statuses.id],
      name: 'payload_locked_documents_rels_project_statuses_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_identity_aliases = pgTable(
  'site_identity_aliases',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    alias: varchar('alias').notNull(),
  },
  (columns) => [
    index('site_identity_aliases_order_idx').on(columns._order),
    index('site_identity_aliases_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_identity.id],
      name: 'site_identity_aliases_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_identity_bio = pgTable(
  'site_identity_bio',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    paragraph: varchar('paragraph').notNull(),
  },
  (columns) => [
    index('site_identity_bio_order_idx').on(columns._order),
    index('site_identity_bio_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_identity.id],
      name: 'site_identity_bio_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_identity_inspirations = pgTable(
  'site_identity_inspirations',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').notNull(),
  },
  (columns) => [
    index('site_identity_inspirations_order_idx').on(columns._order),
    index('site_identity_inspirations_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_identity.id],
      name: 'site_identity_inspirations_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_identity_nav_guide_lines = pgTable(
  'site_identity_nav_guide_lines',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    line: varchar('line'),
  },
  (columns) => [
    index('site_identity_nav_guide_lines_order_idx').on(columns._order),
    index('site_identity_nav_guide_lines_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_identity.id],
      name: 'site_identity_nav_guide_lines_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_identity = pgTable(
  'site_identity',
  {
    id: serial('id').primaryKey(),
    siteName: varchar('site_name').default('Templ3'),
    siteDomain: varchar('site_domain').default('sigterm.vodka'),
    siteEmail: varchar('site_email').default('hello@sigterm.vodka'),
    siteDescription: varchar('site_description').default(
      "Sigterm's personal web: DevSecOps, hacking, hardware, AI, and a retro cyberpunk aesthetic.",
    ),
    wallpaper: integer('wallpaper_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    handle: varchar('handle').default('Sigterm'),
    role: varchar('role').default('DevSecOps / DevOps / Pentester'),
    specialty: varchar('specialty').default('Cloud Infrastructure, Pentesting, Hardware'),
    status: enum_site_identity_status('status').default('active'),
    claim: varchar('claim').default(
      'Architecting secure cloud environments, breaking systems, and hacking stuff.',
    ),
    intro: varchar('intro').default(
      'Cloud infrastructure, offensive security, hacking stuff, and a retro-cyberpunk terminal aesthetic.',
    ),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    navGuideTitle: varchar('nav_guide_title').default('README.txt — How to navigate Templ3'),
    terminalPrompt: varchar('terminal_prompt').default('sigterm@templ3:~$'),
    terminalPwd: varchar('terminal_pwd').default('/home/sigterm'),
    terminalUname: varchar('terminal_uname').default(
      'Templ3 OS 0.6.6.6 sigterm-sanctum x86_64 GNU/Linux',
    ),
    whoamiOutput: varchar('whoami_output').default(
      'Handle:    Sigterm / Sigterm015\nRole:      DevSecOps → Red Team\nStatus:    ACTIVE\nSpecialty: Pentesting, Bug Bounty, Automation\nDomain:    sigterm.vodka\nCodename:  Templ3',
    ),
    neofetchOutput: varchar('neofetch_output'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('site_identity_wallpaper_idx').on(columns.wallpaper),
    index('site_identity_avatar_idx').on(columns.avatar),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_tags = relations(tags, () => ({}))
export const relations_categories = relations(categories, ({ one }) => ({
  icon: one(media, {
    fields: [categories.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [posts.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  category: one(categories, {
    fields: [posts.category],
    references: [categories.id],
    relationName: 'category',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [_posts_v_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_heroImage: one(media, {
    fields: [_posts_v.version_heroImage],
    references: [media.id],
    relationName: 'version_heroImage',
  }),
  version_category: one(categories, {
    fields: [_posts_v.version_category],
    references: [categories.id],
    relationName: 'version_category',
  }),
  _rels: many(_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_projects_stack = relations(projects_stack, ({ one }) => ({
  _parentID: one(projects, {
    fields: [projects_stack._parentID],
    references: [projects.id],
    relationName: 'stack',
  }),
}))
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [projects_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_projects = relations(projects, ({ one, many }) => ({
  projectStatus: one(project_statuses, {
    fields: [projects.projectStatus],
    references: [project_statuses.id],
    relationName: 'projectStatus',
  }),
  stack: many(projects_stack, {
    relationName: 'stack',
  }),
  coverImage: one(media, {
    fields: [projects.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  _rels: many(projects_rels, {
    relationName: '_rels',
  }),
}))
export const relations__projects_v_version_stack = relations(
  _projects_v_version_stack,
  ({ one }) => ({
    _parentID: one(_projects_v, {
      fields: [_projects_v_version_stack._parentID],
      references: [_projects_v.id],
      relationName: 'version_stack',
    }),
  }),
)
export const relations__projects_v_rels = relations(_projects_v_rels, ({ one }) => ({
  parent: one(_projects_v, {
    fields: [_projects_v_rels.parent],
    references: [_projects_v.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [_projects_v_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations__projects_v = relations(_projects_v, ({ one, many }) => ({
  parent: one(projects, {
    fields: [_projects_v.parent],
    references: [projects.id],
    relationName: 'parent',
  }),
  version_projectStatus: one(project_statuses, {
    fields: [_projects_v.version_projectStatus],
    references: [project_statuses.id],
    relationName: 'version_projectStatus',
  }),
  version_stack: many(_projects_v_version_stack, {
    relationName: 'version_stack',
  }),
  version_coverImage: one(media, {
    fields: [_projects_v.version_coverImage],
    references: [media.id],
    relationName: 'version_coverImage',
  }),
  _rels: many(_projects_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_links = relations(links, ({ one }) => ({
  logo: one(media, {
    fields: [links.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations_favourite_media = relations(favourite_media, ({ one }) => ({
  mediaType: one(media_types, {
    fields: [favourite_media.mediaType],
    references: [media_types.id],
    relationName: 'mediaType',
  }),
  progress: one(media_statuses, {
    fields: [favourite_media.progress],
    references: [media_statuses.id],
    relationName: 'progress',
  }),
  coverImage: one(media, {
    fields: [favourite_media.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  blogPost: one(posts, {
    fields: [favourite_media.blogPost],
    references: [posts.id],
    relationName: 'blogPost',
  }),
}))
export const relations__favourite_media_v = relations(_favourite_media_v, ({ one }) => ({
  parent: one(favourite_media, {
    fields: [_favourite_media_v.parent],
    references: [favourite_media.id],
    relationName: 'parent',
  }),
  version_mediaType: one(media_types, {
    fields: [_favourite_media_v.version_mediaType],
    references: [media_types.id],
    relationName: 'version_mediaType',
  }),
  version_progress: one(media_statuses, {
    fields: [_favourite_media_v.version_progress],
    references: [media_statuses.id],
    relationName: 'version_progress',
  }),
  version_coverImage: one(media, {
    fields: [_favourite_media_v.version_coverImage],
    references: [media.id],
    relationName: 'version_coverImage',
  }),
  version_blogPost: one(posts, {
    fields: [_favourite_media_v.version_blogPost],
    references: [posts.id],
    relationName: 'version_blogPost',
  }),
}))
export const relations_notes = relations(notes, () => ({}))
export const relations__notes_v = relations(_notes_v, ({ one }) => ({
  parent: one(notes, {
    fields: [_notes_v.parent],
    references: [notes.id],
    relationName: 'parent',
  }),
}))
export const relations_web_apps = relations(web_apps, () => ({}))
export const relations_media_types = relations(media_types, ({ one }) => ({
  icon: one(media, {
    fields: [media_types.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_media_statuses = relations(media_statuses, ({ one }) => ({
  icon: one(media, {
    fields: [media_statuses.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_project_statuses = relations(project_statuses, ({ one }) => ({
  icon: one(media, {
    fields: [project_statuses.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    linksID: one(links, {
      fields: [payload_locked_documents_rels.linksID],
      references: [links.id],
      relationName: 'links',
    }),
    'favourite-mediaID': one(favourite_media, {
      fields: [payload_locked_documents_rels['favourite-mediaID']],
      references: [favourite_media.id],
      relationName: 'favourite-media',
    }),
    notesID: one(notes, {
      fields: [payload_locked_documents_rels.notesID],
      references: [notes.id],
      relationName: 'notes',
    }),
    'web-appsID': one(web_apps, {
      fields: [payload_locked_documents_rels['web-appsID']],
      references: [web_apps.id],
      relationName: 'web-apps',
    }),
    'media-typesID': one(media_types, {
      fields: [payload_locked_documents_rels['media-typesID']],
      references: [media_types.id],
      relationName: 'media-types',
    }),
    'media-statusesID': one(media_statuses, {
      fields: [payload_locked_documents_rels['media-statusesID']],
      references: [media_statuses.id],
      relationName: 'media-statuses',
    }),
    'project-statusesID': one(project_statuses, {
      fields: [payload_locked_documents_rels['project-statusesID']],
      references: [project_statuses.id],
      relationName: 'project-statuses',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_identity_aliases = relations(site_identity_aliases, ({ one }) => ({
  _parentID: one(site_identity, {
    fields: [site_identity_aliases._parentID],
    references: [site_identity.id],
    relationName: 'aliases',
  }),
}))
export const relations_site_identity_bio = relations(site_identity_bio, ({ one }) => ({
  _parentID: one(site_identity, {
    fields: [site_identity_bio._parentID],
    references: [site_identity.id],
    relationName: 'bio',
  }),
}))
export const relations_site_identity_inspirations = relations(
  site_identity_inspirations,
  ({ one }) => ({
    _parentID: one(site_identity, {
      fields: [site_identity_inspirations._parentID],
      references: [site_identity.id],
      relationName: 'inspirations',
    }),
  }),
)
export const relations_site_identity_nav_guide_lines = relations(
  site_identity_nav_guide_lines,
  ({ one }) => ({
    _parentID: one(site_identity, {
      fields: [site_identity_nav_guide_lines._parentID],
      references: [site_identity.id],
      relationName: 'navGuideLines',
    }),
  }),
)
export const relations_site_identity = relations(site_identity, ({ one, many }) => ({
  wallpaper: one(media, {
    fields: [site_identity.wallpaper],
    references: [media.id],
    relationName: 'wallpaper',
  }),
  aliases: many(site_identity_aliases, {
    relationName: 'aliases',
  }),
  bio: many(site_identity_bio, {
    relationName: 'bio',
  }),
  avatar: one(media, {
    fields: [site_identity.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  inspirations: many(site_identity_inspirations, {
    relationName: 'inspirations',
  }),
  navGuideLines: many(site_identity_nav_guide_lines, {
    relationName: 'navGuideLines',
  }),
}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum_projects_status: typeof enum_projects_status
  enum__projects_v_version_status: typeof enum__projects_v_version_status
  enum_favourite_media_status: typeof enum_favourite_media_status
  enum__favourite_media_v_version_status: typeof enum__favourite_media_v_version_status
  enum_notes_status: typeof enum_notes_status
  enum__notes_v_version_status: typeof enum__notes_v_version_status
  enum_media_types_now_category: typeof enum_media_types_now_category
  enum_media_types_lookup_source: typeof enum_media_types_lookup_source
  enum_site_identity_status: typeof enum_site_identity_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  tags: typeof tags
  categories: typeof categories
  posts: typeof posts
  posts_rels: typeof posts_rels
  _posts_v: typeof _posts_v
  _posts_v_rels: typeof _posts_v_rels
  projects_stack: typeof projects_stack
  projects: typeof projects
  projects_rels: typeof projects_rels
  _projects_v_version_stack: typeof _projects_v_version_stack
  _projects_v: typeof _projects_v
  _projects_v_rels: typeof _projects_v_rels
  links: typeof links
  favourite_media: typeof favourite_media
  _favourite_media_v: typeof _favourite_media_v
  notes: typeof notes
  _notes_v: typeof _notes_v
  web_apps: typeof web_apps
  media_types: typeof media_types
  media_statuses: typeof media_statuses
  project_statuses: typeof project_statuses
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_identity_aliases: typeof site_identity_aliases
  site_identity_bio: typeof site_identity_bio
  site_identity_inspirations: typeof site_identity_inspirations
  site_identity_nav_guide_lines: typeof site_identity_nav_guide_lines
  site_identity: typeof site_identity
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_tags: typeof relations_tags
  relations_categories: typeof relations_categories
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations__posts_v_rels: typeof relations__posts_v_rels
  relations__posts_v: typeof relations__posts_v
  relations_projects_stack: typeof relations_projects_stack
  relations_projects_rels: typeof relations_projects_rels
  relations_projects: typeof relations_projects
  relations__projects_v_version_stack: typeof relations__projects_v_version_stack
  relations__projects_v_rels: typeof relations__projects_v_rels
  relations__projects_v: typeof relations__projects_v
  relations_links: typeof relations_links
  relations_favourite_media: typeof relations_favourite_media
  relations__favourite_media_v: typeof relations__favourite_media_v
  relations_notes: typeof relations_notes
  relations__notes_v: typeof relations__notes_v
  relations_web_apps: typeof relations_web_apps
  relations_media_types: typeof relations_media_types
  relations_media_statuses: typeof relations_media_statuses
  relations_project_statuses: typeof relations_project_statuses
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_identity_aliases: typeof relations_site_identity_aliases
  relations_site_identity_bio: typeof relations_site_identity_bio
  relations_site_identity_inspirations: typeof relations_site_identity_inspirations
  relations_site_identity_nav_guide_lines: typeof relations_site_identity_nav_guide_lines
  relations_site_identity: typeof relations_site_identity
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
